name: r
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - r=3.6
  - r-aws.s3
  - r-base
  - r-broom
  - r-car
  - r-classint
  - r-covr
  - r-data.table
  - r-dbi
  - r-deldir
  - r-dplyr
  - r-egg
  - r-essentials
  - r-fs
  - r-geojsonio
  - r-geojsonsf
  - r-geor
  - r-geosphere
  - r-ggnewscale
  - r-ggplot2
#  - r-ggspatial
  - r-ggtext
  - r-gridExtra
  - r-gstat
  - r-hdf5r
  - r-irkernel
  - r-jpeg
  - r-knitr
  - r-leafem
  - r-leaflet
  - r-lidR
  - r-lwgeom
  - r-mapdata
  - r-mapproj
  - r-maps
  - r-maptools
  - r-mapview
  - r-microbenchmark
  - r-ncdf4
  - r-nlme
  - r-patchwork
  - r-plyr
  - r-pool
  - r-proj4
  - r-protolite
  - r-randomFields
  - r-randomForest
  - r-raster
  - r-rcolorbrewer
  - r-readxl
  - r-reticulate
#  - r-rgee
  - r-rgeos
  - r-rlas
  - r-rlist
  - r-rmarkdown
  - r-rnaturalearth
#  - r-rnaturalearthdata
  - r-RNetCDF
#  - r-rockchalk
  - r-rodbc
  - r-RPostgres
  - r-RPostgreSQL
  - r-RSQLite
  - r-rstac
  - r-scales
  - r-sf
  - r-snow
  - r-spacetime
#  - r-spatialreg
  - r-spatstat
  - r-spdep
  - r-stars
  - r-stringr
#  - r-terra
  - r-testthat
  - r-tibble
#  - r-tidync
  - r-tidyr
  - r-tidyverse
  - r-tmap
  - r-units
  - r-viridis
  - pip
  - pip:
    - ff
    - grid
variables:
  MAAP_CONF: '/maap-py/'