name: r
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - anywidget=0.9.18
  - awscli=2.23.9
  - backoff=2.2.1
  # - basemap
  - bioconductor-rhdf5=2.50.0
  - boto3=1.39.8
  - cython=3.1.2
  - earthaccess=0.14.0
  - earthengine-api=1.6.2
  - gdal=3.9.2
  - geocube=0.7.1
  - geopandas=1.1.1
  - groff=1.23.0
  - h5py=3.13.0
  - httpx=0.28.1
  - lonboard=0.9.3
  - mapclassify=2.10.0
  - matplotlib=3.10.5
  - mizani=0.13.5
  - mpl-scatter-density=0.8
  - numba=0.61.2
  - numpy=2.2.6
  - pandas=2.3.1
  - pandarallel=1.6.5
  - parallel=20250622
  - perl=5.32.1
  - postgis=3.5.0
  - pycurl=7.45.6
  - pyogrio=0.10.0
  - pyproj=3.7.1
  - pystac-client=0.6.1
  - python=3.13.5
  - r=4.4
  - r-arrow=18.1.0
  - r-aws.s3=0.3.22
  - r-base=4.4.1
  - r-BiocManager=1.30.26
  - r-broom=1.0.9
  - r-car=3.1_3
  - r-chron=2.3_62
  - r-classint=0.4_11
  - r-covr=3.6.4
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-deldir=2.0_4
  - r-dplyr=1.1.4
  - r-egg=0.4.5
  - r-essentials=4.4
  - r-fs=1.6.6
  - r-future=1.67.0 # Geotrees focused
  # r-geojsonio
  - r-geojsonsf=2.0.3
  - r-geor=1.9_5
  - r-geosphere=1.5_20
  - r-ggnewscale=0.5.2
  - r-ggplot2=3.5.2
  - r-ggpubr=0.6.1 # Geotrees focused
  - r-ggspatial=1.1.9
  - r-ggtext=0.1.2
  - r-gridExtra=2.3
  - r-gstat=2.1_4
  - r-gsubfn=0.7
  - r-hdf5r=1.3.12
  - r-httr2=1.2.1 # Geotrees focused
  - r-irkernel=1.3.2
  - r-jpeg=0.1_11
  - r-knitr=1.50
  - r-leafem=0.2.4
  - r-leaflet=2.2.2
  - r-lidR=4.1.2
  - r-lwgeom=0.2_14
  - r-mapdata=2.3.1
  - r-mapproj=1.2.12
  - r-maps=3.4.3
  - r-mapview=2.11.2
  - r-microbenchmark=1.5.0
  - r-minpack.lm=1.2_4 # for BIOMASS
  - r-ncdf4=1.24
  - r-nlme=3.1_168
  - r-partykit=1.2_24
  - r-patchwork=1.3.1
  - r-paws=0.9.0
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-pool=1.0.4
  - r-proj4=1.0_14
  - r-proto=1.0.0
  - r-protolite=2.3.1
  - r-randomFields=3.3.14
  - r-randomForest=4.7_1.2
  - r-raster=3.6_32
  - r-rcolorbrewer=1.1_3
  - r-rcsf=1.0.2 # Geotrees focused
  - r-readxl=1.4.5
  - r-reticulate=1.43.0
  - r-rgee=1.1.7
  - r-rlas=1.6.2
  - r-rlist=0.4.6.2
  - r-rmarkdown=2.29
  - r-rnaturalearth=1.0.1
  - r-rnaturalearthdata=1.0.0
  - r-RNetCDF=2.11_1
  - r-rockchalk=1.8.157
  - r-rodbc=1.3_26
  - r-RPostgres=1.4.7
  - r-RPostgreSQL=0.7_7
  - r-RSQLite=2.4.2
  - r-rstac=1.0.1
  # r-rstoolbox
  - r-scales=1.4.0
  - r-sf=1.0_18
  - r-snow=0.4_4
  - r-spacetime=1.3_3
  - r-spatialreg=1.3_6
  - r-spatstat=3.4_0
  - r-spdep=1.3_11
  - r-sqldf=0.4_11
  - r-stars=0.6_6
  - r-stringr=1.5.1
  - r-terra=1.7_83
  - r-testthat=3.2.3
  - r-tibble=3.3.0
  - r-tidync=0.4.0
  - r-tidyr=1.3.1
  - r-tidyverse=2.0.0
  - r-tmap=3.3_4
  - r-units=0.8_7
  - r-viridis=0.6.5
  - rasterio
  - rasterstats=0.20.0
  - requests=2.32.4
  - rio-cogeo=5.4.2
  - rtree=1.4.0
  - s3fs=2025.7.0
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - seaborn=0.13.2
  - shapely=2.0.6
  - sliderule=4.17.1
  - statsmodels=0.14.5
  - tqdm=4.67.1
  - unidecode=1.3.8
  - unzip=6.0
  - xmltodict=0.13.0
  - pip=24.3.1
  - pip:
    - ff==0.0.10
    - grid==0.7.1
    - maap-py==4.2.0
    - morecantile==6.1.0
    - rio-tiler==7.2.2