name: r
channels:
  - conda-forge
  - r
  - nodefaults
dependencies:
  - anywidget=0.9.13
  - awscli=2.19.1
  - backoff=2.2.1
  - basemap=1.4.1
  - boto3=1.35.23
  - cython=3.0.11
  - earthaccess=0.11.0
  - earthengine-api=1.1.3
  - gdal=3.9.1
  - geocube=0.7.0
  - geopandas=1.0.1
  - groff=1.22.4
  - h5py=3.11.0
  - httpx=0.27.2
  - icu
  - lonboard=0.9.3
  - mapclassify=2.8.1
  - matplotlib=3.8.4
  - mizani=0.12.2
  - mpl-scatter-density=0.7
  - numba=0.60.0
  - numpy=1.26.4
  - pandas=2.2.3
  - pandarallel=1.6.5
  - parallel=20240922
  - perl=5.32.1
  - postgis=3.4.2
  - pycurl=7.45.3
  - pyogrio=0.9.0
  - pyproj=3.6.1
  - pystac-client=0.7.5  
  - python=3.10.13
  - r=4.2
  - r-arrow=16.1.0
  - r-aws.s3=0.3.22
  - r-base=4.2.3
  - r-BiocManager=1.30.23
  - r-broom=1.0.6
  - r-car=3.1_2
  - r-chron=2.3_61
  - r-classint=0.4_10
  - r-covr=3.6.4
  - r-data.table=1.15.4
  - r-dbi=1.2.3
  - r-deldir=2.0_4
  - r-devemf=4.0_2
  - r-dplyr=1.1.4
  - r-egg=0.4.5
  - r-essentials=4.2
  - r-fs=1.6.4
  - r-geojsonio=0.11.3
  - r-geojsonsf=2.0.3
  - r-geor=1.9_4
  - r-geosphere=1.5_18
  - r-ggnewscale=0.4.10
  - r-ggplot2=3.5.1
  - r-ggspatial=1.1.9
  - r-ggtext=0.1.2
  - r-gridExtra=2.3
  - r-gstat=2.1_1
  - r-gsubfn=0.7
  - r-hdf5r=1.3.10
  - r-irkernel=1.3.2
  - r-jpeg=0.1_10
  - r-knitr=1.47
  - r-leafem=0.2.3
  - r-leaflet=2.2.2
  - r-lidR=4.1.1
  - r-lwgeom=0.2_14
  - r-mapdata=2.3.1
  - r-mapproj=1.2.11
  - r-maps=3.4.2
  - r-maptools=1.1_8
  - r-mapview=2.11.2
  - r-microbenchmark=1.4.10
  - r-ncdf4=1.22
  - r-nlme=3.1_165
  - r-patchwork=1.2.0
  - r-paws=0.6.0
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-pool=1.0.3
  - r-proj4=1.0_14
  - r-proto=1.0.0
  - r-protolite=2.3.0
  - r-randomFields=3.3.14
  - r-randomForest=4.7_1.1
  - r-raster=3.6_26
  - r-rcolorbrewer=1.1_3
  - r-readxl=1.4.3
  - r-reticulate=1.38.0
  - r-rgdal=1.5_32
  - r-rgee=1.1.7
  - r-rgeos=0.6_4
  - r-rlas=1.6.2
  - r-rlist=0.4.6.2 
  - r-rmarkdown=2.27
  - r-rnaturalearth=1.0.1
  - r-rnaturalearthdata=1.0.0
  - r-RNetCDF=2.9_2
  - r-rockchalk=1.8.157
  - r-rodbc=1.3_23
  - r-RPostgres=1.4.7
  - r-RPostgreSQL=0.7_6
  - r-RSQLite=2.3.4
  - r-rstac=0.9.2_5
  - r-scales=1.3.0
  - r-sf=1.0_16
  - r-snow=0.4_4
  - r-spacetime=1.3_1
  - r-spatialreg=1.3_3
  - r-spatstat=3.0_7
  - r-spdep=1.3_5
  - r-sqldf=0.4_11
  - r-stars=0.6_5
  - r-stringi
  - r-stringr
  - r-terra=1.7_78
  - r-testthat=3.2.1.1 
  - r-tibble=3.2.1
  - r-tidync=0.3.0
  - r-tidyr=1.3.1
  - r-tidyverse=2.0.0
  - r-tmap=3.3_4
  - r-units=0.8_5
  - r-viridis=0.6.5
  - rasterio=1.3.10
  - rasterstats=0.20.0
  - requests=2.32.2 
  - rio-cogeo=5.3.6
  - rtree=1.3.0
  - s3fs=2024.10.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - shapely=2.0.4
  - sliderule=4.7.1
  - statsmodels=0.14.4
  - tqdm=4.66.5
  - unidecode=1.3.8
  - unzip=6.0
  - xmltodict=0.13.0
  - pip=24.2
  - pip:
    - ff==0.0.10
    - grid==0.7.1
    - morecantile==6.1.0
    - rio-tiler==7.2.2
    - git+https://github.com/MAAP-Project/maap-py.git@develop