name: r
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli=2.14.1
  - earthaccess=0.8.2
  - parallel=20231122
  - perl=5.32.1
  - postgis=3.4.0
  - python=3.10.13
  - r=4.3
  - r-aws.s3=0.3.22
  - r-base=4.3.1
  - r-biocmanager=1.30.22
  - r-broom=1.0.5
  - r-classint=0.4_10
  - r-covr=3.6.4
  - r-data.table=1.14.10