name: r
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - awscli
  - pystac-client
  - python=3.13.5
  - r-base=4.4.3
  - r-irkernel
  - r-reticulate
  - r-sf # installed as dependency
  - requests
  - pip=24.3.1
  - pip:
    - ff==0.0.10
    - grid==0.7.1
    - maap-py==4.2.0
    - morecantile==6.2.0
    - rio-tiler==7.8.1