name: r
channels:
  - conda-forge
  - r
  - nodefaults
dependencies:
  - awscli=2.14.1
  - earthaccess=0.8.2
  - parallel=20231122
  - perl=5.32.1
  - postgis=3.4.0
  - python=3.10.13
  - r=4.2
  - r-arrow=14.01
  - r-aws.s3=0.3.22
  - r-base=4.2.3
  - r-BiocManager=1.30.22
  - r-broom=1.0.5
  - r-car=3.1_2
  - r-chron=2.3_61
  - r-classint=0.4_10
  - r-covr=3.6.4
  - r-data.table=1.14.10
  - r-dbi=1.1.3
  - r-deldir=2.0_2
  - r-devemf=4.0_2
  - r-dplyr=1.1.4
  - r-egg=0.4.5
  - r-essentials=4.2
  - r-fs=1.6.3
  - r-geojsonio=0.11.3
  - r-geojsonsf=2.0.3
  - r-geor=1.9_2
  - r-geosphere=1.5_18
  - r-ggnewscale=0.4.9
  - r-ggplot2=3.4.4
  - r-ggspatial=1.1.9
  - r-ggtext=0.1.2
  - r-gridExtra=2.3
  - r-gstat=2.1_1
  - r-gsubfn=0.7
  - r-hdf5r=1.3.8
  - r-irkernel=1.3.2
  - r-jpeg=0.1_10
  - r-knitr=1.45
  - r-leafem=0.2.3
  - r-leaflet=2.2.1
  - r-lidR=4.0.4
  - r-lwgeom=0.2_13
  - r-mapdata=2.3.1
  - r-mapproj=1.2.11
  - r-maps=3.4.1.1
  - r-maptools=1.1_8
  - r-mapview=2.11.2
  - r-microbenchmark=1.4.10
  - r-ncdf4=1.22
  - r-nlme=3.1_164
  - r-patchwork=1.1.3
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-pool=1.0.1
  - r-proj4=1.0_13
  - r-proto=1.0.0
  - r-protolite=2.3.0
  - r-randomFields=3.3.14
  - r-randomForest=4.7_1.1
  - r-raster=3.6_26
  - r-rcolorbrewer=1.1_3
  - r-readxl=1.4.3
  - r-reticulate=1.34.0
  - r-rgee=1.1.7
  - r-rgeos=0.6_4
  - r-rlas=1.6.2
  - r-rlist=0.4.6.2
  - r-rmarkdown=2.25
  - r-rnaturalearth=0.3.4
  - r-rnaturalearthdata=0.1.0
  - r-RNetCDF=2.6_2
  - r-rockchalk=1.8.157
  - r-rodbc=1.3_23
  - r-RPostgres=1.4.5
  - r-RPostgreSQL=0.7_5
  - r-RSQLite=2.3.4
  - r-rstac=0.9.2_5
  - r-scales=1.3.0
  - r-sf=1.0_14
  - r-snow=0.4_4
  - r-spacetime=1.3_1
  - r-spatialreg=1.3_1
  - r-spatstat=3.0_7
  - r-spdep=1.3_1
  - r-sqldf=0.4_11
  - r-stars=0.6_4
  - r-stringr=1.5.1
  - r-terra=1.7_55
  - r-testthat=3.2.1
  - r-tibble=3.2.1
  - r-tidync=0.3.0
  - r-tidyr=1.3.0
  - r-tidyverse=2.0.0
  - r-tmap=3.3_4
  - r-units=0.8_5
  - r-viridis=0.6.4
  - pip=23.3.2
  - pip:
    - ff==0.0.10
    - grid==0.7.1
variables:
  MAAP_CONF: '/maap-py/'