name: r
channels:
  - conda-forge
  - r
  - nodefaults
dependencies:
 - anywidget=0.9.12
  - awscli=2.14.1 
  - backoff=2.2.1
  - basemap=1.3.7
  - boto3=1.34.106
  - cython=3.0.10
  - earthaccess=0.9.0
  - earthengine-api=0.1.404
  - gdal=3.7.0
  - geocube=0.5.2
  - geopandas=0.14.4
  - groff=1.22.4
  - h5py=3.9.0
  - httpx=0.27.0
  - lonboard=0.9.3
  - mapclassify=2.6.1
  - matplotlib=3.7.3
  - mizani=0.11.4
  - mpl-scatter-density=0.7
  - numba=0.59.1
  - numpy=1.26.4
  - pandas=2.2.2
  - pandarallel=1.6.5
  - parallel=20240522
  - perl=5.32.1
  - postgis=3.3.3
  - pycurl=7.45.1
  - pyogrio=0.6.0
  - pyproj=3.5.0
  - pystac-client=0.7.5 
  - python=3.10.13
  - r=4.2
  - rasterio=1.3.7
  - rasterstats=0.19.0
  - requests=2.32.2
  - rio-cogeo=5.3.0
  - rtree=1.2.0
  - s3fs=2024.5.0
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - seaborn=0.13.2
  - shapely=2.0.1
  - sliderule=4.4.0
  - statsmodels=0.14.2
  - tqdm=4.66.4
  - unidecode=1.3.8
  - unzip=6.0
  - xmltodict=0.13.0
  - pip=24.2
  - pip:
    - ff==0.0.10
    - grid==0.7.1
    - morecantile==5.4.2
    - rio-tiler==6.7.0
    - git+https://github.com/MAAP-Project/maap-py.git@v4.1.0