name: r
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - anywidget
  - awscli
  - backoff
  - basemap
  - bioconductor-rhdf5
  - boto3
  - cython
  - earthaccess
  - earthengine-api
  - gdal
  - geocube
  - geopandas
  - groff
  - h5py
  - httpx
  - lonboard
  - mapclassify
  - matplotlib
  - mizani
  - mpl-scatter-density
  - numba
  - numpy
  - pandas
  - pandarallel
  - parallel
  - perl
  - postgis
  - pycurl
  - pyogrio
  - pyproj
  - pystac-client
  - python
  - r=4.4
  - r-arrow
  - r-aws.s3
  - r-base
  - r-BiocManager
  - r-broom
  - r-car
  - r-chron
  - r-classint
  - r-covr
  - r-data.table
  - r-dbi
  - r-deldir
  - r-dplyr
  - r-egg
  - r-essentials
  - r-fs
  - r-future
  - r-geojsonio
  - r-geojsonsf
  - r-geor
  - r-geosphere
  - r-ggnewscale
  - r-ggplot2
  - r-ggpubr
  - r-ggspatial
  - r-ggtext
  - r-gridExtra
  - r-gstat
  - r-gsubfn
  - r-hdf5r
  - r-httr2
  - r-irkernel
  - r-jpeg
  - r-knitr
  - r-lasr
  - r-leafem
  - r-leaflet
  - r-lidR
  - r-lwgeom
  - r-mapdata
  - r-mapproj
  - r-maps
  - r-maptools
  - r-mapview
  - r-microbenchmark
  - r-minpack.lm
  - r-ncdf4
  - r-nlme
  - r-partykit
  - r-patchwork
  - r-paws
  - r-plogr
  - r-plyr
  - r-png
  - r-pool
  - r-proj4
  - r-proto
  - r-protolite
  - r-randomFields
  - r-randomForest
  - r-raster
  - r-rcolorbrewer
  - r-rcsf
  - r-readxl
  - r-reticulate
  - r-rgdal
  - r-rgee
  - r-rgeos
  - r-rlas
  - r-rlist
  - r-rmarkdown
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-RNetCDF
  - r-rockchalk
  - r-rodbc
  - r-RPostgres
  - r-RPostgreSQL
  - r-RSQLite
  - r-rstac
  - r-rstoolbox
  - r-scales
  - r-sf
  - r-snow
  - r-spacetime
  - r-spatialreg
  - r-spatstat
  - r-spdep
  - r-sqldf
  - r-stars
  - r-stringr
  - r-terra
  - r-testthat
  - r-tibble
  - r-tidync
  - r-tidyr
  - r-tidyverse
  - r-tmap
  - r-units
  - r-viridis
  - rasterio
  - rasterstats
  - requests
  - rio-cogeo
  - rtree
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sliderule
  - statsmodels
  - tqdm
  - unidecode
  - unzip
  - xmltodict
  - pip
  - pip:
    - ff==0.0.10
    - grid==0.7.1
    - maap-py==4.2.0
    - morecantile==6.1.0
    - rio-tiler==7.2.2