name: r
channels:
  - conda-forge
  - r
  - nodefaults
dependencies:
  - anywidget=0.9.13
  - awscli=2.19.1
  - backoff=2.2.1
  - basemap=1.4.1
  - boto3=1.35.23
  - pip=24.2
  - pip:
    - ff==0.0.10
    - grid==0.7.1
    - morecantile==5.3.0
    - rio-tiler==6.6.1
    - git+https://github.com/MAAP-Project/maap-py.git@develop