name: r
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli=2.14.1
  - earthaccess=0.8.2
  - parallel=20231122
  - perl=5.32.1
  - postgis=3.4.0
  - python=3.10.13
  - r=4.3
  - r-aws.s3=0.3.22
  - r-base=4.3.1
  - r-biocmanager=1.30.22
  - r-broom=1.0.5
  - r-classint=0.4_10
  - r-covr=3.6.4
  - r-data.table=1.14.10
  - r-dbi=1.1.3
  - r-deldir=2.0_2
  - r-dplyr=1.1.4
  - r-egg=0.4.5
  - r-essentials=4.3
  - r-fs=1.6.3
  - r-geojsonio=0.11.3
  - r-geojsonsf=2.0.3
  - r-geor=1.9_2
  - r-geosphere=1.5_18
  - r-ggnewscale=0.4.9
  - r-ggplot2=3.4.4
  - r-ggspatial=1.1.9
  - r-ggtext=0.1.2
  - r-gridExtra=2.3
  - r-gstat=2.1_1
  - r-hdf5r=1.3.8
  - r-irkernel=1.3.2
  - r-jpeg=0.1_10
  - r-knitr=1.45
  - r-leafem=0.2.3