name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Python packages only - NO R packages in conda
  - gdal=3.10.2
  - nodejs=20.19.5
  - rtree=1.4.1 
  - unzip=6.0
  - pip=26.0
  - pip:
    # - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6
    - morecantile==6.1.0
    - rio-tiler==7.2.2