name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget=0.9.13
  - awscli
  - backoff=2.2.1
  - basemap
  - bokeh=3.5.2
  - boto3=1.35.23
  - bottleneck=1.4.2
  - cartopy=0.24.0
  - cdsapi=0.7.4
  - cf_xarray=0.10.0
  - cfgrib=0.9.14.1
  - cython=3.0.11
  - dask-ml=2024.4.4
  - datashader=0.16.3
  - descartes=1.1.0
  - earthaccess
  - earthengine-api=1.1.1
  - eofs=1.4.1
  - erddapy=2.2.3
  - esmpy
  - fastjmd95=0.2.1
  - flox=0.9.12
  - fsspec
  - gcm_filters=0.5.0
  - gdal
  - geocube
  - geogif=0.1.5
  - geopandas=0.7.0
  - geopy=2.4.1
  - geoviews-core=1.13.0
  - groff=1.22.4
  - h5netcdf=1.4.0
  - h5py=3.12.1
  - hdf5
  - holoviews=1.19.1
  - httpx=0.27.2
  - hvplot
  - intake-esm=2023.11.10
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.7.0
  - intake=2.0.7
  - kerchunk=0.2.6
  - line_profiler=4.1.3
  - lonboard
  - lxml
  - lz4=4.3.3
  - mapclassify
  - matplotlib
  - memory_profiler=0.61.0
  - metpy=1.6.3
  - mizani=0.12.2
  - mpl-scatter-density=0.7
  - nc-time-axis=1.4.1
  - netcdf4
  - numba=0.60.0
  - numbagg=0.8.2
  - numcodecs
  - numpy
  - odc-stac=0.3.10
  - pandarallel=1.6.5
  - pandas=2.2.3
  - pyarrow
  - pycamhd=0.7.0
  - pycurl=7.45.1
  - pydap=3.5
  - pyogrio
  - pyproj
  - pystac-client
  - pystac
  - python-blosc
  - python
  - rasterio
  - rasterstats=0.19.0
  - rechunker=0.5.2
  - requests=2.32.3
  - rio-cogeo
  - rioxarray=0.17.0
  - rtree=1.3.0
  - s3fs
  - satpy
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - shapely
  - sliderule=4.6.4
  - sparse=0.15.4
  - stackstac=0.5.1
  - statsmodels
  - tiledb-py
  - timezonefinder
  - tqdm=4.66.5
  - unidecode=1.3.8
  - unzip=6.0
  - xarray-datatree=0.0.14
  - xarray-spatial=0.4.0
  - xarray
  - xarrayutils=2.0.1
  - xbatcher=0.4.0
  - xcape
  - xclim
  - xcube
  - xesmf=0.8.7
  - xgboost=2.1.1
  - xgcm=0.8.1
  - xhistogram=0.3.2
  - xmip=0.7.2
  - xmitgcm=0.5.2
  - xmltodict=0.13.0
  - xpublish=0.3.3
  - xrft=1.0.1
  - zarr=2.18.3
  - pip=24.2
  - pip:
    - morecantile==5.4.2
    - rio-tiler==6.7.0
    - git+https://github.com/MAAP-Project/maap-py.git@v4.1.0