name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget~=0.9
  - awscli
  - backoff
  #- basemap
  - bokeh~=3.5
  - boto3~=1.35
  - bottleneck~=1.4
  - cartopy~=0.24
  - cdsapi~=0.7
  - cf_xarray~=0.10
  - cfgrib~=0.9.14
  - cython
  - dask-ml~=2024.4
  - datashader~=0.16
  - descartes~=1.1
  - earthaccess~=0.11
  - earthengine-api
  - eofs~=1.4
  - erddapy~=2.2
  - esmpy~=8.6
  - fastjmd95~=0.2
  - flox~=0.9
  - fsspec~=2024.10
  - gcm_filters~=0.5
  - gdal~=3.9
  - geocube~=0.7
  - geogif>=0.1.4
  - geopandas~=1.0
  - geopy~=2.4
  - geoviews-core~=1.13
  - groff
  - h5netcdf~=1.4
  - h5py~=3.12
  - hdf5~=1.14
  - holoviews~=1.20
  - httpx~=0.27
  - hvplot~=0.11
  - intake-esm~=2023.11
  - intake-geopandas~=0.4
  - intake-stac~=0.4
  - intake-xarray~=0.7
  - intake~=2.0
  - kerchunk~=0.2
  - line_profiler~=4.1
  - lonboard~=0.10
  - lxml~=5.3
  - lz4~=4.3
  - mapclassify~=2.8
  - matplotlib
  - memory_profiler~=0.61
  - metpy~=1.6
  - mizani
  - mpl-scatter-density
  - nc-time-axis~=1.4
  - netcdf4~=1.7
  - numba~=0.60
  - numbagg~=0.8
  - numcodecs~=0.13
  - numpy~=2.0
  - odc-stac~=0.3
  - pandarallel
  - pandas~=2.2
  - pyarrow~=17.0
  - pycamhd~=0.7
  - pycurl
  - pydap~=3.5
  - pyogrio~=0.10
  - pyproj~=3.7
  - pystac-client~=0.8
  - pystac~=1.11
  - python-blosc~=1.11
  - python
  - rasterio~=1.4
  - rasterstats
  - rechunker~=0.5
  - requests~=2.32
  - rio-cogeo~=5.3
  - rioxarray~=0.17
  - rtree
  - s3fs~=2024.10
  - satpy~=0.53
  - scikit-image~=0.24
  - scikit-learn~=1.5
  - scipy~=1.14
  - seaborn~=0.13
  - shapely~=2.0
  - sliderule
  - sparse~=0.15
  - stackstac~=0.5
  - statsmodels~=0.14
  - tiledb-py~=0.32
  - timezonefinder~=6.5
  - tqdm~=4.67
  - unidecode
  - unzip
  - xarray-datatree
  - xarray-spatial~=0.4
  - xarray~=2024.10
  - xarrayutils~=2.0
  - xbatcher~=0.4
  #- xcape
  - xclim~=0.53
  - xcube
  - xesmf~=0.8
  - xgboost~=2.1
  - xgcm~=0.8
  - xhistogram~=0.3
  - xmip~=0.7
  - xmitgcm~=0.5
  - xmltodict
  - xpublish~=0.3
  - xrft~=1.0
  - zarr~=2.18
  - pip=24.2
  - pip:
    - morecantile==5.4.2
    - rio-tiler==6.7.0
    - git+https://github.com/MAAP-Project/maap-py.git@develop
