name: base
channels:
  - defaults
dependencies:
  - bokeh
  - boto3
  - bottleneck
  - cartopy
  - cfgrib
  - cython
  - dask-ml
  - datashader
  - descartes
  - earthaccess
  - eofs
  - erddapy
  - esmpy
  - flox
  - fsspec
  - gcm_filters
  - gdal
  - geocube
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - kerchunk
  - lxml
  - lz4
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numba
  - numcodecs
  - numpy
  - odc-stac
  - pandas
  - pyarrow
  - pydap
  - pygeos
  - pyproj
  - pystac
  - pystac-client
  - python-blosc
  - rasterio
  - rechunker
  - rio-cogeo
  - rioxarray
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sparse
  - stackstac
  - xarray
  - xarray-datatree
  - xarray-spatial
  - xarrayutils
  - xesmf
  - xhistogram
  - zarr