name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cython=0.29.33
  - gdal=3.6.2
  - h5py=3.7.0
  - matplotlib=3.6.2
  - numba=0.56.4
  - pygeos=0.14
  - pyproj=3.4.1
  - rasterio=1.3.4
  - scipy=1.10.0