name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget=0.9.13
  - awscli=2.14.1  
  - backoff=2.2.1
  - basemap=1.3.7
  - bokeh=3.5.2
  - boto3=1.35.23
  - bottleneck=1.4.0
  - cartopy=0.23.0
  - cdsapi=0.7.3
  - cf_xarray=0.9.5
  - cfgrib=0.9.14.1
  - cython=3.0.11
  - dask-ml=2024.4.4
  - datashader=0.16.3
  - descartes=1.1.0
  - earthaccess=0.10.0
  - earthengine-api=1.1.1
  - eofs=1.4.1
  - erddapy=2.2.3
  - esmpy=8.4.2
  - fastjmd95=0.2.1
  - flox=0.9.12
  - fsspec=2024.9.0
  - gcm_filters=0.3.0
  - gdal=3.7.0
  - geocube=0.5.3
  - geogif=0.1.5
  - geopandas=0.14.4
  - geopy=2.4.1
  - geoviews-core=1.13.0
  - groff=1.22.4
  - h5netcdf=1.3.0
  - h5py=3.9.0
  - hdf5=1.14.0
  - holoviews=1.19.1
  - httpx=0.27.2
  - hvplot=0.10.0
  - intake-esm=2023.11.10
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.7.0
  - intake=2.0.7
  - kerchunk=0.2.6
  - line_profiler=4.1.3
  - lonboard=0.9.3
  - lxml=4.9.3
  - lz4=4.3.3
  - mapclassify=2.8.0
  - matplotlib=3.7.3
  - memory_profiler=0.61.0
  - metpy=1.6.3
  - mizani=0.12.2
  - mpl-scatter-density=0.7
  - nc-time-axis=1.4.1
  - netcdf4=1.6.4
  - numba=0.60.0
  - numbagg=0.8.2
  - numcodecs=0.13.0
  - numpy=1.26.4
  - odc-stac=0.3.10
  - pandarallel=1.6.5
  - pandas=2.2.3
  - pyarrow=14.0.1
  - pycamhd=0.7.0
  - pycurl=7.45.1
  - pydap=3.5
  - pyogrio=0.6.0
  - pyproj=3.5.0
  - pystac-client=0.8.0 
  - pystac=1.10.1
  - python-blosc=1.11.1
  - python=3.10.13
  - rasterio=1.3.7
  - rasterstats=0.19.0
  - rechunker=0.5.2
  - requests=2.32.3
  - rio-cogeo=5.3.4
  - rioxarray=0.17.0
  - rtree=1.3.0
  - s3fs=2024.9.0
  - satpy=0.51.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - shapely=2.0.1
  - sliderule=4.6.4
  - sparse=0.15.4
  - stackstac=0.5.1
  - statsmodels=0.14.3
  - tiledb-py=0.19.1
  - timezonefinder=6.5.3
  - tqdm=4.66.5
  - unidecode=1.3.8
  - unzip=6.0
  - xarray-datatree=0.0.14
  - xarray-spatial=0.4.0
  - xarray=2024.9.0
  - xarrayutils=2.0.1
  - xbatcher=0.4.0
  - xcape=0.1.4
  - xclim=0.52.2
  - xcube=1.5.1
  - xesmf=0.8.7
  - xgboost=2.1.1
  - xgcm=0.8.1
  - xhistogram=0.3.2
  - xmip=0.7.2
  - xmitgcm=0.5.2
  - xmltodict=0.13.0
  - xpublish=0.3.3
  - xrft=1.0.1
  - zarr=2.18.3
  - pip=24.2
  - pip:
    - morecantile==5.4.2
    - rio-tiler==6.7.0
    - git+https://github.com/MAAP-Project/maap-py.git@develop
