name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli=2.14.1 # Downgrade suggested but not taken: 1.32.106
  - backoff=2.2.1
  - basemap=1.3.7
  - bokeh=3.4.1
  - boto3=1.34.106
  - bottleneck=1.3.8
  - cartopy=0.23.0
  - cdsapi=0.7.0
  - cf_xarray=0.9.0
  - cfgrib=0.9.11.0
  - cython=3.0.10
  - dask-ml=2024.3.20
  - datashader=0.16.1
  - descartes=1.1.0
  - earthaccess=0.9.0
  - earthengine-api=0.1.403
  - eofs=1.4.1
  - erddapy=2.2.0
  - esmpy=8.4.2
  - fastjmd95=0.2.1
  - flox=0.9.7
  - fsspec=2024.5.0
  - gcm_filters=0.3.0
  - gdal=3.7.0 # Downgrade suggested but not taken: 3.6.4
  - geocube=0.5.2
  - geogif=0.1.5
  - geopandas=0.14.4
  - geopy=2.4.1
  - geoviews-core=1.12.0
  - groff=1.22.4
  - h5netcdf=1.3.0
  - h5py=3.9.0
  - hdf5=1.14.0
  - holoviews=1.18.3
  - httpx=0.27.0
  - hvplot=0.10.0
  - intake-esm=2024.2.6 # Downgrade suggested but not taken: 2023.11.10
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.7.0
  - intake=2.0.5
  - kerchunk=0.2.5
  - line_profiler=4.1.1
  - lxml=4.9.3
  - lz4=4.3.3
  - mapclassify=2.6.1
  - matplotlib=3.7.3
  - memory_profiler=0.61.0
  - metpy=1.6.2
  - mizani=0.11.3
  - mpl-scatter-density=0.7
  - nc-time-axis=1.4.1
  - netcdf4=1.6.4
  - numba=0.59.1
  - numbagg=0.8.1
  - numcodecs=0.12.1
  - numpy=1.26.4
  - odc-stac=0.3.9
  - pandarallel=1.6.5
  - pandas=2.2.2
  - pyarrow=14.0.1
  - pycamhd=0.7.0
  - pycurl=7.45.1
  - pydap=3.4.0
  - pygeos=0.14
  - pyogrio=0.6.0
  - pyproj=3.5.0
  - pystac-client=0.8.0
  - pystac=1.10.1
  - python-blosc=1.11.1
  - python=3.10.13
  - rasterio=1.3.7
  - rasterstats=0.19.0
  - rechunker=0.5.2
  - requests=2.32.1
  - rio-cogeo=5.3.0
  - rioxarray=0.15.5
  - rtree=1.2.0
  - s3fs=2024.5.0
  - satpy=0.48.0
  - scikit-image=0.22.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - seaborn=0.13.2
  - shapely=2.0.1
  - sliderule=4.4.0
  - sparse=0.15.3
  - stackstac=0.5.0
  - statsmodels=0.14.2
  - tiledb-py=0.19.1
  - timezonefinder=6.4.1 # Downgrade suggested but not taken: 6.4.0
  - tqdm=4.66.4
  - unidecode=1.3.8
  - xarray-datatree=0.0.14
  - xarray-spatial=0.4.0
  - xarray=2024.5.0
  - xarrayutils=2.0.1
  - xbatcher=0.3.0
  - xcape=0.1.4
  - xclim=0.49.0
  - xcube=1.5.1
  - xesmf=0.8.5
  - xgboost=2.0.3
  - xgcm=0.8.1
  - xhistogram=0.3.2
  - xmip=0.7.2
  - xmitgcm=0.5.2
  - xmltodict=0.13.0
  - xpublish=0.3.3
  - xrft=1.0.1
  - zarr=2.18.1
  - pip=24.0
  - pip:
    - morecantile==5.3.0
    - rio-tiler==6.6.1
variables:
  MAAP_CONF: '/maap-py/'