name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget=0.9.13
  - awscli
  - backoff
  #- basemap
  - bokeh=3.5.2
  - boto3=1.35.36
  - bottleneck=1.4.2
  - cartopy=0.24.0
  - cdsapi=0.7.4
  - cf_xarray=0.10.0
  - cfgrib=0.9.14.1
  #- cython
  - dask-ml=2024.4.4
  - datashader=0.16.3
  - descartes=1.1.0
  - earthaccess=0.11.0
  - earthengine-api
  - eofs=1.4.1
  - erddapy=2.2.3
  - esmpy=8.6.1
  - fastjmd95=0.2.1
  - flox=0.9.14
  - fsspec=2024.10.0
  - gcm_filters=0.5.0
  - gdal=3.9.3
  - geocube=0.7.0
  #- geogif
  - geopandas=1.0.1
  - geopy=2.4.1
  - geoviews-core=1.13.0
  - groff
  - h5netcdf=1.4.0
  - h5py=3.12.1
  - hdf5=1.14.3
  - holoviews=1.20.0
  - httpx=0.27.2
  - hvplot=0.11.1
  - intake-esm=2023.11.10
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.7.0
  - intake=2.0.7
  - kerchunk=0.2.6
  - line_profiler=4.1.3
  - lonboard=0.10.3
  - lxml=5.3.0
  - lz4=4.3.3
  - mapclassify=2.8.1
  - matplotlib
  - memory_profiler=0.61.0
  - metpy=1.6.3
  - mizani
  - mpl-scatter-density
  - nc-time-axis=1.4.1
  - netcdf4=1.7.1
  - numba=0.60.0
  - numbagg=0.8.2
  - numcodecs=0.13.1
  - numpy=2.0.2
  - odc-stac=0.3.10
  #- pandarallel
  - pandas=2.2.3
  - pyarrow=17.0.0
  - pycamhd=0.7.0
  #- pycurl
  - pydap=3.5.1
  - pyogrio=0.10.0
  - pyproj=3.7.0
  - pystac-client=0.8.5
  - pystac=1.11.0
  - python-blosc=1.11.2
  - python
  - rasterio=1.4.2
  #- rasterstats
  - rechunker=0.5.2
  - requests=2.32.3
  - rio-cogeo=5.3.6
  - rioxarray=0.17.0
  #- rtree
  - s3fs=2024.10.0
  - satpy=0.53.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - shapely=2.0.6
  #- sliderule
  - sparse=0.15.4
  - stackstac=0.5.1
  - statsmodels=0.14.4
  - tiledb-py=0.32.5
  - timezonefinder=6.5.4
  - tqdm=4.67.0
  #- unidecode
  - unzip
  #- xarray-datatree
  - xarray-spatial=0.4.0
  - xarray=2024.10.0
  - xarrayutils=2.0.1
  - xbatcher=0.4.0
  #- xcape
  - xclim=0.53.1
  #- xcube
  - xesmf=0.8.8
  - xgboost=2.1.2
  - xgcm=0.8.1
  - xhistogram=0.3.2
  - xmip=0.7.2
  - xmitgcm=0.5.2
  - xmltodict
  - xpublish=0.3.3
  - xrft=1.0.1
  - zarr=2.18.3
  - pip=24.2
  - pip:
    - morecantile==5.4.2
    - rio-tiler==6.7.0
    - git+https://github.com/MAAP-Project/maap-py.git@develop
