name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli=2.14.1
  - backoff=2.2.1
  - basemap=1.3.7
  - bokeh=3.3.3
  - boto3=1.34.41
  - bottleneck=1.3.7
  - cartopy=0.22.0
  - cdsapi=0.6.1
  - cf_xarray=0.9.0
  - cfgrib=0.9.10.4
  - cython=3.0.7
  - dask-ml=2023.3.24
  - datashader=0.16.0
  - descartes=1.1.0
  - earthaccess=0.8.2
  - earthengine-api=0.1.384
  - eofs=1.4.0
  - erddapy=2.2.0
  - esmpy=8.4.2
  - fastjmd95=0.2.1
  - flox=0.8.6
  - fsspec=2023.12.2
  - gcm_filters=0.3.0
  - gdal=3.7.0
  - geocube=0.4.2
  - geogif=0.1.5
  - geopandas=0.14.2
  - geopy=2.4.1
  - geoviews-core=1.11.0
  - groff=1.22.4
  - h5netcdf=1.3.0
  - h5py=3.9.0
  - hdf5=1.14.0
  - holoviews=1.18.1
  - httpx=0.26.0
  - hvplot=0.9.1
  - intake-esm=2024.2.6
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.7.0
  - intake=0.7.0
  - kerchunk=0.2.2
  - line_profiler=4.1.1
  - lxml=4.9.3
  - lz4=4.3.2
  - mapclassify=2.6.1
  - matplotlib=3.7.3
  - memory_profiler=0.61.0
  - metpy=1.6.1
  - mizani=0.10.0
  - mpl-scatter-density=0.7
  - nc-time-axis=1.4.1
  - netcdf4=1.6.4
  - numba=0.58.1
  - numbagg=0.8.0
  - numcodecs=0.11.0
  - numpy=1.26.3
  - odc-stac=0.3.8
  - pandarallel=1.6.5
  - pandas=2.1.4
  - pyarrow=14.0.1
  - pycamhd=0.7.0
  - pycurl=7.45.1
  - pydap=3.4.0
  - pygeos=0.14
  - pyogrio=0.6.0
  - pyproj=3.5.0
  - pystac-client=0.6.1
  - pystac=1.9.0
  - python-blosc=1.10.6
  - python=3.10.13
  - rasterio=1.3.7
  - rasterstats=0.19.0
  - rechunker=0.5.2
  - requests=2.31.0
  - rio-cogeo=5.1.1
  - rioxarray=0.15.0
  - rtree=1.1.0
  - s3fs=2023.12.2
  - satpy=0.47.0
  - scikit-image=0.22.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.1
  - shapely=2.0.1
  - sliderule=4.1.0
  - sparse=0.15.0
  - stackstac=0.5.0
  - statsmodels=0.14.1
  - tiledb-py=0.19.1 
  - timezonefinder=6.4.1
  - tqdm=4.66.1
  - unidecode=1.3.7
  - xarray-datatree=0.0.13
  - xarray-spatial=0.3.5
  - xarray=2023.12.0
  - xarrayutils=2.0.0
  - xbatcher=0.3.0
  - xcape=0.1.4
  - xclim=0.46.0
  - xcube=0.9.1
  - xesmf=0.8.2
  - xgboost=2.0.3
  - xgcm=0.8.1
  - xhistogram=0.3.2
  - xmip=0.7.2
  - xmitgcm=0.5.2
  - xmltodict=0.13.0
  - xpublish=0.3.3
  - xrft=1.0.1
  - zarr=2.16.1
  - pip=23.3.2
  - pip:
    - morecantile==5.1.0
    - rio-tiler==6.2.8
variables:
  MAAP_CONF: '/maap-py/'