name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli=2.14.1
  - backoff=2.2.1
  - basemap
  - bokeh=3.3.2
  - boto3=1.33.13
  - bottleneck=1.3.7
  - cartopy=0.22.0
  - cfgrib=0.9.10.4
  - cython=3.0.7
  - dask-ml=2023.3.24
  - datashader=0.16.0
  - descartes=1.1.0
  - earthaccess=0.8.2
  - earthengine-api=0.1.384
  - eofs=1.4.0
  - erddapy=2.2.0
  - esmpy=8.4.2
  - flox=0.8.5
  - fsspec=2023.12.2
  - gcm_filters=0.3.0
  - gdal=3.7.0
  - geocube=0.4.2
  - geopandas=0.14.1
  - geoviews-core=1.11.0
  - h5netcdf=1.3.0
  - h5py=3.9.0
  - hdf5=1.14.1
  - holoviews=1.18.1
  - httpx=0.25.2
  - hvplot=0.9.0
  - intake=0.7.0
  - intake-geopandas=0.4.0
  - intake-stac=0.4.0
  - intake-xarray=0.7.0
  - kerchunk=0.2.2
  - lxml=4.9.3
  - lz4=4.3.2
  - mapclassify=2.6.1
  - matplotlib=3.8.2
  - mizani
  - mpl-scatter-density=0.7
  - nc-time-axis=1.4.1
  - netcdf4=1.6.4
  - numba=0.58.1
  - numcodecs=0.11.0
  - numpy=1.26.2
  - odc-stac=0.3.8
  - pandas=2.1.4
  - pandarallel
  - python=3.10.13
  - pyarrow=14.0.1
  - pycurl=7.45.1
  - pydap=3.4.0
  - pygeos=0.14
  - pyogrio=0.6.0
  - pyproj=3.6.1
  - pystac=1.9.0
  - pystac-client=0.6.1
  - python-blosc=1.10.6
  - rasterio=1.3.8
  - rasterstats=0.19.0
  - rechunker=0.5.2
  - requests=2.31.0
  - rio-cogeo=5.1.0
  - rioxarray=0.15.0
  - rtree=1.1.0
  - s3fs=2023.12.2
  - scikit-image=0.22.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.0
  - shapely=2.0.1
  - sliderule=4.1.0
  - sparse=0.14.0
  - stackstac=0.5.0
  - statsmodels=0.14.1
  - tqdm=4.66.1
  - unidecode=1.3.7
  - xarray=2023.12.0
  - xarray-datatree=0.0.13
  - xarray-spatial=0.3.5
  - xarrayutils=2.0.0
  - xesmf=0.8.2
  - xhistogram=0.3.2
  - xmltodict=0.13.0
  - zarr=2.16.1
  - pip=23.3.2
  - pip:
    - morecantile
variables:
  MAAP_CONF: '/maap-py/'