name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli
  - backoff
  - basemap
  - bokeh
  - boto3
  - bottleneck
  - cartopy
  - cfgrib
  - cython
  - dask-ml
  - datashader
  - descartes
  - earthaccess
  - earthengine-api
  - eofs
  - erddapy
  - esmpy
  - flox
  - fsspec
  - gcm_filters
  - gdal
  - geocube
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - hdf5
  - holoviews
  - httpx
  - hvplot
  - intake
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - kerchunk
  - lxml
  - lz4
  - mapclassify
  - matplotlib
  - mizani
  - mpl-scatter-density
  - nc-time-axis
  - netcdf4
  - numba
  - numcodecs
  - numpy
  - odc-stac
  - pandas
  - pandarallel
  - python=3.10.13
  - pyarrow
  - pycurl
  - pydap
  - pygeos
  - pyogrio
  - pyproj
  - pystac
  - pystac-client
  - python-blosc
  - rasterio
  - rasterstats
  - rechunker
  - requests
  - rio-cogeo
  - rioxarray
  - rtree
  - s3fs
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sliderule
  - sparse
  - stackstac
  - statsmodels
  - tqdm
  - unidecode
  - xarray
  - xarray-datatree
  - xarray-spatial
  - xarrayutils
  - xesmf
  - xhistogram
  - xmltodict
  - zarr
  - pip=23.3.2
  - pip:
    - morecantile
variables:
  MAAP_CONF: '/maap-py/'