---
displayName: "Pangeo"
description: "Pangeo workspace version: 3.1.5"
tags: ["Pangeo", "JupyterLab", "MAAP"]
icon: /devfiles/pangeo/devfile/pangeo_simple_logo.svg
links: 
  self: "/devfiles/pangeo/devfile/devfile.yaml"
globalMemoryLimit: 2710Mi
