name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - icu=78.2
  - nodejs=22.22.0
  - rustac=0.9.7
  - pip=26.0
  - pip:
    - rio-tiler==8.0.5
    - maap-py==4.2.0
    - maap-algorithms-jupyter-extension==0.5.1
    - maap-jupyter-server-extension==3.0.0
    - maap-dps-jupyter-extension==0.7.7
    # - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.2
    - maap-libs-jupyter-extension==1.2.5
    - maap-user-workspace-management-jupyter-extension==1.0.0