name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - icu=78.2
  - nodejs=22.22.0
  - rustac=0.9.9
  - pip=26.1.1
  - pip:
    - rio-tiler==9.0.6
    - git+https://github.com/MAAP-Project/jupyter-server-extension.git@v3.0.0
    - git+https://github.com/MAAP-Project/maap-py.git@v5.1.0a2
    - git+https://github.com/MAAP-Project/algorithms-jupyter-extension.git@v1.0.0
    - git+https://github.com/MAAP-Project/dps-jupyter-extension.git@v2.0.0
    # - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.2
    - maap-libs-jupyter-extension==1.2.5
    - maap-user-workspace-management-jupyter-extension==1.0.0