name: python
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget=0.9.13
  - awscli=2.14.1 
  - backoff=2.2.1
  - basemap
  - boto3=1.35.37
  - cython=3.0.11
  - earthengine-api=1.1.3
  - gdal
  - geocube=0.7.0
  - geopandas=1.0.1
  - groff=1.22.4
  - h5py=3.11.0
  - hdf5=1.14.3
  - httpx=0.27.2
  - lonboard=0.10.2
  - mapclassify=2.8.1
  - matplotlib=3.8.4
  - mizani=0.12.2
  - mpl-scatter-density=0.7
  - numba=0.60.0
  - numpy=1.26.4
  - pandas=2.2.3
  - pandarallel=1.6.5
  - pycurl=7.45.3
  - pyogrio
  - pyproj=3.6.1
  - pystac-client=0.7.5 
  - python=3.10.13
  - rasterio=1.3.10
  - rasterstats=0.20.0
  - requests=2.31.0
  - rio-cogeo=5.3.6
  - rtree=1.3.0
  - s3fs=2024.9.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - shapely=2.0.4
  - sliderule=4.7.1
  - statsmodels=0.14.4
  - tqdm=4.66.5
  - unidecode=1.3.8
  - unzip=6.0
  - xmltodict=0.14.1
  - pip=24.2
  - pip:
    - morecantile==5.4.2
    - rio-tiler==6.7.0
    - git+https://github.com/MAAP-Project/maap-py.git@v4.1.0