name: python
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget=0.9.13
  - awscli=2.19.4
  - backoff
  - boto3=1.35.36
  - cython
  - earthengine-api
  - fsspec=2024.10.0
  - gdal=3.9.3
  - geopandas=1.0.1
  - groff
  - h5py=3.12.1
  - hdf5=1.14.3
  - httpx=0.27.2
  - hvplot=0.11.1
  - isce3
  - lonboard
  - mapclassify=2.8.1
  - matplotlib
  - mpl-scatter-density
  - numba=0.60.0
  - numpy
  - pandas=2.2.3
  - pycurl
  - pyogrio=0.10.0
  - pyOpenSSL=23.1.1
  - pyproj=3.7.0
  - pystac-client=0.8.5
  - python=3.12.7
  - rasterio=1.4.2
  - rasterstats
  - requests=2.32.3
  - rio-cogeo=5.3.6
  - rtree
  - s3fs=2024.10.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - shapely=2.0.6
  - sliderule
  - statsmodels=0.14.4
  - tqdm=4.67.0
  - unidecode
  - unzip
  - xmltodict
  - xarray=2024.10.0
  - pip=24.3.1
  - pip:
    - morecantile==6.1.0
    - rio-tiler==7.2.2
    - git+https://github.com/MAAP-Project/maap-py.git@develop
