---
displayName: "MAAP CARDAMOM"
description: Latest version of MAAP CARDAMOM
tags: ["JupyterLab", "Python", "MAAP", "CARDAMOM"]
icon: /devfiles/cardamom/devfile/cardamom.png
globalMemoryLimit: 2710Mi