name: WORKSPACE_ENVIRONMENT_NAME
channels:
  - conda-forge
  - nodefaults
dependencies:
  - folium=0.18.0
  - gitpython=3.1.43
  - ipyleaflet=0.19.2
  - jupyter_server=2.14.2
  - jupyterlab=4.3.0
  - jupyterlab-git=0.50.2
  - jupyterlab_widgets=3.0.13
  - nodejs=22.12.0 # isce3 is 22.12.0 python is 22.12.0 R is 22.6.0 
  - notebook=6.4.12 # Should not upgrade yet because appears notebook v7 doesnt support extensions
  - plotly=5.24.1 # isce3 is 5.24.1 python is 5.24.1 R is 5.24.1
  - plotnine=0.14.4 # isce3 0.14.4 python is 0.14.4 R is 0.14.4
  - pip=24.3.1
  - pip:
    - jupyter-resource-usage==1.1.0
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
    - maap-algorithms-jupyter-extension==0.3.6
    - maap-che-sidebar-visibility-jupyter-extension==1.1.2
    - maap-dps-jupyter-extension==0.7.2
    - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.0
    - maap-jupyter-server-extension==2.1.0
    - maap-libs-jupyter-extension==1.2.4
    - maap-user-workspace-management-jupyter-extension==0.1.3
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-pgstac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
