name: WORKSPACE_ENVIRONMENT_NAME
channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupyter_server=2.14.2
  - jupyterlab=4.3.0
  - nodejs
  - notebook=6.4.12 # Should not upgrade yet because appears notebook v7 doesnt support extensions
  - pip=24.3.1
  - pip:
    - jupyter-resource-usage==1.1.0
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
    - maap-algorithms-jupyter-extension==0.3.9
    - maap-che-sidebar-visibility-jupyter-extension==1.1.2
    - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.0
    - maap-jupyter-server-extension==2.1.2
    - maap-libs-jupyter-extension==1.2.4
    - maap-user-workspace-management-jupyter-extension==0.1.3
    - maap-dps-jupyter-extension==0.7.6
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-pgstac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
