name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black=24.8.0
  - folium=0.17.0
  - gh-scoped-creds=4.1
  - gh=2.57.0
  - git-lfs=3.5.1
  - gitpython=3.1.43
  - ipyevents=2.0.2
  - ipyleaflet=0.19.2
  - ipytree=0.2.2
  - ipywidgets=8.1.5
  - jupyter_server=2.14.2
  - jupyter-panel-proxy=0.1.0
  - jupyterlab_widgets=3.0.13
  - jupyterlab-git=0.50.1
  - jupyterlab=4.2.5
  - nb_conda=2.2.1
  - nb_conda_kernels=2.5.1
  - nbstripout=0.7.1
  - nodejs=20.1.0  
  - pangeo-notebook=2024.09.01
  - plotly=5.24.1
  - plotnine
  - pydantic=2.9.2
  - python-gist=0.10.6
  - python-graphviz=0.20.3
  - rise=5.7.1
  - snakeviz=2.2.0
  - xarray_leaflet=0.2.3
  - pip=24.2
  - pip:
    - jupyter-resource-usage==1.1.0
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
    - rio-tiler==6.7.0
    - maap-algorithms-jupyter-extension==0.3.6
    - maap-che-sidebar-visibility-jupyter-extension==1.1.2
    - maap-dps-jupyter-extension==0.7.1
    - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.0
    - maap-jupyter-server-extension==2.0.8
    - maap-libs-jupyter-extension==1.2.4
    - maap-user-workspace-management-jupyter-extension==0.1.3
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-stac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
