name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black=24.4.2
  - folium=0.16.0
  - gh-scoped-creds=4.1
  - gh=2.50.0
  - git-lfs=3.5.1
  - gitpython=3.1.43
  - ipyevents=2.0.2
  - ipyleaflet=0.19.1
  - ipytree=0.2.2
  - ipywidgets=8.1.3
  - jupyter_server=2.12.5
  - jupyter-panel-proxy=0.1.0
  - jupyterlab_widgets=3.0.11
  - jupyterlab-git=0.50.0
  - jupyterlab-s3-browser=0.12.0
  - jupyterlab=4.1.6
  - nb_conda=2.2.1
  - nb_conda_kernels=2.5.1
  - nbstripout=0.7.1
  - nodejs=18.15.0
  - notebook=6.4.12
  - pangeo-notebook=0.0.2
  - plotly=5.22.0
  - plotnine=0.12.2
  - pydantic=2.7.3
  - python-gist=0.10.6
  - python-graphviz=0.20.3
  - snakeviz=2.2.0
  - xarray_leaflet=0.2.3
  - pip=24.0
  - pip:
    - jupyter-resource-usage==0.7.2
    - rio-tiler==6.2.8
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
    - maap-algorithms-jupyter-extension==0.3.1
    - maap-che-sidebar-visibility-jupyter-extension==1.1.2
    - maap-dps-jupyter-extension==0.7.1
    - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.0
    - maap-jupyter-server-extension==2.0.7
    - maap-libs-jupyter-extension==1.2.3
    - maap-user-workspace-management-jupyter-extension==0.1.2
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-stac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
