---
displayName: "Python (default)"
description: "Basic MAAP Python workspace"
tags: ["JupyterLab", "Python", "MAAP"]
icon: /devfiles/python/devfile/python-logo-generic.svg
links: 
  self: "/devfiles/python/devfile/devfile.yaml"
globalMemoryLimit: 2710Mi
