name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget=0.9.21
  - awscli=1.44.31
  - backoff=2.2.1
  - boto3=1.42.41
  - cython=3.2.4
  - earthengine-api=1.7.12
  - fsspec=2026.1.0
  - gdal=3.11.5
  - geopandas=1.1.2
  - groff=1.23.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - httpx=0.28.1
  - hvplot=0.12.2
  - isce3=0.25.7
  - jupyterlab=4.5.2
  - lonboard=0.13.0
  - mapclassify=2.10.0
  - matplotlib=3.10.8
  - mpl-scatter-density=0.8
  - nodejs=25.2.1
  - numba=0.63.1
  - numpy=2.3.5
  - pandas=2.2.2
  - pycurl=7.45.7
  - pyproj=3.7.2
  #- pyogrio causes dependency conflicts with isce3
  - pyopenssl=25.3.0
  #- rasterio causes dependency conflicts with isce3
  #- rasterstats causes dependency conflicts with isce3
  - requests=2.32.5
  #- rio-cogeo causes dependency conflicts with isce3
  - rtree=1.4.1
  - s3fs=0.4.2
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - seaborn=0.13.2
  - shapely=2.1.2
  - sliderule=5.0.6
  - statsmodels=0.14.6
  - tqdm=4.67.3
  - unidecode=1.4.0
  - unzip=6.0
  - xarray=2026.1.0
  - pip=26.0
  - pip:
    - jupyter-resource-usage==1.2.0
    # - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6
    - morecantile==6.1.0
    - rio-tiler==7.2.2
    - maap-py==4.2.0
    - maap-algorithms-jupyter-extension==0.5.1
    - maap-jupyter-server-extension==3.0.0
    - maap-dps-jupyter-extension==0.7.7
    # - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.2
    - maap-libs-jupyter-extension==1.2.5
    - maap-user-workspace-management-jupyter-extension==1.0.0
variables:
  TITILER_STAC_ENDPOINT: 'https://openveda.cloud/api/stac'
  TITILER_ENDPOINT: 'https://openveda.cloud/api/raster'
  STAC_CATALOG_NAME: 'VEDA STAC'
  STAC_CATALOG_URL: 'https://openveda.cloud/api/stac'
  STAC_BROWSER_URL: 'https://openveda.cloud/'