---
displayName: "MAAP ISCE3/PLAnT"
description: Latest version of MAAP ISCE3
tags: ["JupyterLab", "Python", "MAAP", "ISCE3", "PLAnT"]
icon: /devfiles/isce3/devfile/jupyter.png
globalMemoryLimit: 2710Mi
