name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pangeo-notebook=2023.04.15
  - gitpython=3.1.30
  - ipyleaflet=0.17.2
  - jupyterlab=3.6.3
  - jupyterlab-git=0.34.2
  - jupyter-packaging=0.12.3
  - jupyterlab_widgets=3.0.7
  - nodejs=18.15.0
  - plotly=5.14.1
  - xmltodict=0.13.0