name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli
  - gitpython
  - gh
  - git-lfs
  - ipyevents
  - ipyleaflet
  - ipywidgets
  - jupyterlab=3.6.1
  - jupyterlab-git=0.34.2
  - jupyter-packaging=0.12.3
  - jupyterlab_widgets=3.0.7
  - nbstripout
  - nodejs=18.15.0
  - pangeo-notebook
  - plotly
  - pydantic
  - rioxarray
  - shapely
  - xarray_leaflet
  - xmltodict
  - pip
  - pip:
    - jupyter-resource-usage==0.7.2
    - jupyter-server==2.5.0
    - rio_tiler
    - pystac_client
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.5#egg-info=stac_ipyleaflet
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-stac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
