name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black=24.2.0
  - folium=0.15.1
  - gh-scoped-creds=4.1
  - gh=2.40.1
  - git-lfs=3.4.1
  - gitpython=3.1.40
  - ipyevents=2.0.2
  - ipyleaflet=0.18.1
  - ipytree=0.2.2
  - ipywidgets=8.0.6
  - jupyter-packaging=0.12.3
  - jupyter-panel-proxy=0.1.0
  - jupyterlab_widgets=3.0.7
  - jupyterlab-git=0.34.2
  - jupyterlab-s3-browser=0.12.0
  - jupyterlab=3.6.3
  - nb_conda_kernels=2.3.1
  - nbstripout=0.6.1
  - nodejs=18.15.0
  - pangeo-notebook=2023.04.15
  - plotly=5.18.0
  - plotnine=0.12.2
  - pydantic=2.5.2
  - python-gist=0.10.6
  - python-graphviz=0.20.1
  - rise=5.7.1
  - snakeviz=2.2.0
  - xarray_leaflet=0.2.3
  - pip=23.3.2
  - pip:
    - jupyter-resource-usage==0.7.2
    - rio-tiler==6.2.8
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-stac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
