name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli
  - gitpython
  - gh
  - git-lfs
  - ipyevents
  - ipyleaflet
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyter-packaging
  - jupyterlab_widgets
  - nbstripout
  - nodejs
  - pangeo-notebook
  - plotly
  - pydantic
  - rioxarray
  - shapely
  - xarray_leaflet
  - xmltodict
  - pip
  - pip:
    - rio_tiler
    - pystac_client
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.5#egg-info=stac_ipyleaflet
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-stac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
