---
displayName: "ISCE2"
description: "ISCE2 MAAP workspace (version 4.2.0)"
tags: ["JupyterLab", "Python", "MAAP", "ISCE2"]
icon: /devfiles/isce2/devfile/isce.png
links: 
  self: "/devfiles/isce2/devfile/devfile.yaml"
globalMemoryLimit: 2710Mi
