name: WORKSPACE_ENVIRONMENT_NAME
channels:
  - conda-forge
  - nodefaults
dependencies:
  - folium=0.15.1
  - gitpython=3.1.40
  - ipyleaflet=0.18.1
  - jupyterlab=3.6.3
  - jupyterlab-git=0.34.2
  - jupyter-packaging=0.12.3
  - jupyterlab_widgets=3.0.7
  - nodejs=18.15.0
  - plotly=5.18.0
  - plotnine=0.12.2
  - pip=23.3.2
  - pip:
    - jupyter-resource-usage==0.7.2
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
    - maap-algorithms-jupyter-extension==0.3.0
    - maap-che-sidebar-visibility-jupyter-extension==1.1.0
    - maap-dps-jupyter-extension==0.7.0
    - maap-edsc-jupyter-extension==1.1.0
    - maap-help-jupyter-extension==1.3.1
    - maap-libs-jupyter-extension==1.2.0
    - maap-user-workspace-management-jupyter-extension==0.1.0
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-stac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
