name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gitpython=3.1.26
  - ipyleaflet=0.17.2
  - jupyterlab=3.6.1
  - jupyterlab-git=0.34.2
  - jupyter-packaging=0.12.3
  - jupyterlab_widgets=1.0.2
  - nodejs=16.14.2
  - plotly=5.5.0
  - xmltodict=0.13.0
  - pip
    - git+https://github.com/MAAP-Project/che-sidebar-visibility-jupyter-extension.git@develop#egg-info=che-sidebar-visibility-jupyter-extension