name: WORKSPACE_ENVIRONMENT_NAME
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gitpython=3.1.26
  - ipyleaflet=0.17.2
  - jupyterlab=3.6.1
  - jupyterlab-git=0.34.2
  - jupyter-packaging=0.12.3
  - jupyterlab_widgets=3.0.7
  - nodejs=18.15.0
  - plotly=5.5.0
  - xmltodict=0.13.0