name: WORKSPACE_ENVIRONMENT_NAME
channels:
  - conda-forge
  - nodefaults
dependencies:
  - folium=0.16.0
  - gitpython=3.1.43
  - ipyleaflet=0.19.1
  - jupyter_server=2.12.5
  - jupyterlab=4.2.0
  - jupyterlab-git=0.50.0
  - jupyterlab_widgets=3.0.10 
  - nodejs=20.1.0 # Works with: 20.1.0 # Downgrade suggested but not taken: 12.4.0, trying to manually upgrade to avoid error messages 
  - notebook=6.4.12 # Should not upgrade yet because appears notebook v7 doesnt support extensions
  - plotly=5.22.0 # make sure this is compatible in jupyter labextension list 
  - plotnine=0.13.6
  - xmltodict
  - pip=24.0 # Potentially remove because already in base images but check for errors in the console 
  - pip:
    - jupyter-resource-usage==1.0.2
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
variables:
  TITILER_STAC_ENDPOINT: 'https://titiler-stac.maap-project.org/'
  TITILER_ENDPOINT: 'https://titiler.maap-project.org/'
  STAC_CATALOG_NAME: 'MAAP STAC'
  STAC_CATALOG_URL: 'https://stac.maap-project.org/'
  STAC_BROWSER_URL: 'https://stac-browser.maap-project.org/'
