name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip=26.1.1
  - pip:
    - git+https://github.com/MAAP-Project/jupyter-server-extension.git@develop
    - git+https://github.com/MAAP-Project/maap-py.git@v5.1.0a2
    - git+https://github.com/MAAP-Project/algorithms-jupyter-extension.git@develop
    - git+https://github.com/MAAP-Project/dps-jupyter-extension.git@develop
    # - maap-edsc-jupyter-extension==1.1.1
    - maap-help-jupyter-extension==2.0.2
    - maap-libs-jupyter-extension==1.2.5
    - git+https://github.com/MAAP-Project/user-workspace-management-jupyter-extension.git@develop