stages:
  - build

vanilla:
  stage: build

  before_script:
  - docker info

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash base_images/build-image.sh vanilla
    - cat built_images.txt
    - export BASE_IMAGE_NAME=$(tail -1 built_images.txt)
    - bash jupyterlab3/build-image.sh

  tags:
    - shell

  only:
    variables:
      - $BASE_IMAGE_BUILD
    refs:
      - main

pangeo:
  stage: build

  before_script:
  - docker info

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash base_images/build-image.sh pangeo
    - cat built_images.txt
    - export BASE_IMAGE_NAME=$(tail -1 built_images.txt)
    - bash pangeo/build-image.sh

  tags:
    - shell

  only:
    variables:
      - $BASE_IMAGE_BUILD
    refs:
      - main

r:
  stage: build

  before_script:
  - docker info
  # TODO: Uncomment after the initial CI build!
  # - docker inspect -f '{{.State.Running}}' registry

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash base_images/build-image.sh r
    - export BASE_IMAGE_NAME=$(tail -1 built_images.txt)
    - bash jupyterlab3/build-image.sh

  tags:
    - shell

  only:
    refs:
      - main
    variables:
      - $BASE_IMAGE_BUILD

rgedi:
  stage: build

  before_script:
  - docker info
  # TODO: Uncomment after the initial CI build!
  # - docker inspect -f '{{.State.Running}}' registry

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash base_images/build-image.sh rgedi
    - export BASE_IMAGE_NAME=$(tail -1 built_images.txt)
    - bash jupyterlab3/build-image.sh

  tags:
    - shell

  only:
    refs:
      - main
    variables:
      - $BASE_IMAGE_BUILD

rsgislib:
  stage: build

  before_script:
  - docker info

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash base_images/build-image.sh rsgislib
    - cat built_images.txt
    - export BASE_IMAGE_NAME=$(tail -1 built_images.txt)
    - bash jupyterlab3/build-image.sh

  tags:
    - shell

  only:
    variables:
      - $BASE_IMAGE_BUILD
    refs:
      - main


miniconda3:
  stage: build

  before_script:
  - docker info

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash jupyterlab3/build-image.sh

  tags:
    - shell

  only:
    refs:
      - main

  except:
    variables:
      - $BASE_IMAGE_BUILD

edav:
  stage: build

  before_script:
  - docker info

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash edav/build-image.sh

  tags:
    - shell

  only:
    refs:
      - main

  except:
    variables:
      - $BASE_IMAGE_BUILD

isce2:
  stage: build

  before_script:
  - docker info

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash base_images/build-image.sh isce2
    - cat built_images.txt
    - export BASE_IMAGE_NAME=$(tail -1 built_images.txt)
    - bash jupyterlab3/build-image.sh

  tags:
    - shell

  only:
    variables:
      - $BASE_IMAGE_BUILD
    refs:
      - main
