build_image:
  stage: build

  before_script:
  - docker info
  # TODO: Uncomment after the initial CI build!
  # - docker inspect -f '{{.State.Running}}' registry

  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - git clone https://github.com/MAAP-Project/maap-workspaces.git
    - pushd maap-workspaces
    - LATEST_COMMIT=$(git log -n 1 --all --format='%h')
    - git checkout ${LATEST_COMMIT}
    - bash jupyterlab3/build-image.sh

  tags:
    - shell

  only:
   - main
